### ISSUE TITLE
dpctl pip install broken on windows for python3.11

### ISSUE THREAD

**Issue by icfaust** [IntelPython/dpctl#1745]
System info:
```
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2995 Mhz
```
Using python3.11

Reproducer
```
python -m venv env2
env2\Scripts\activate.bat
python -m pip install dpctl
python -c "import dpctl"
```
![image](https://github.com/user-attachments/assets/3c6d8827-8a66-454a-9e90-e9550866e1cb)

Not sure if I am doing something wrong, but I am seeing this failure locally and in github action VMs using pip

**Comment by icfaust** [comment]
temporary fix:
```
import os, site
path_to_env = site.getsitepackages()[0]
path_to_libs = os.path.join(path_to_env, "Library", "bin")
os.add_dll_directory(path_to_libs)
import dpctl
```

**Comment by icfaust** [comment]
here is a rough github workflow which can show the error. also when fixed it doesnt show any devices (second error?)
```
name: oneDAL DPCPP nightly sklearnex
on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
  DPCTL_VERSION: 0.17.0
  DPNP_VERSION: 0.15.0

jobs:
dpctl:
    name: dpctl_test
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dpctl
        shell: cmd
        run: |
          set PATH=C:\msys64\usr\bin;%PATH%
          python -m venv env2
          call .\env2\Scripts\activate.bat
          set DPCTL_SUPPORTED=3.9 3.11
          FOR %%i IN (%DPCTL_SUPPORTED%) DO if ${{ env.PYTHON_VERSION }}==%%i pip install dpctl==${{ env.DPCTL_VERSION }} dpnp==${{ env.DPNP_VERSION }}
          python -c "import os, os.path, site; path_to_env = site.getsitepackages()[0]; path_to_libs = os.path.join(path_to_env, 'Library', 'bin'); temp=os.add_dll_directory(path_to_libs) if os.path.exists(path_to_libs) else None; import dpctl; print(dpctl.get_devices())"
          python -c "import dpctl; print(dpctl.get_devices())"
          pip list
```
